version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app  # For local development; remove in production
      - /app/node_modules  # Anonymous volume for node_modules
    ports:
      - "5000:5000"  # Maps port 5000 on host to port 5000 in the container
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/mydatabase  # Update as needed
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Maps port 5173 in the container to 3000 on the host
    environment:
      - VITE_API_URL=http://backend:5000
    networks:
      - app-network

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"  # Maps port 27017 on host to port 27017 in the container
    volumes:
      - mongo-data:/data/db  # Persistent storage for MongoDB
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
